# Generated by Django 2.1.15 on 2020-04-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroshop', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_desc', models.CharField(max_length=200)),
                ('product_price', models.CharField(max_length=100)),
                ('product_tax', models.CharField(max_length=100)),
            ],
        ),
    ]
