# Generated by Django 3.0.7 on 2020-06-30 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('facilites', models.TextField()),
                ('rent', models.CharField(max_length=200)),
                ('images', models.FileField(null=True, upload_to='media/uploads')),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
