# Generated by Django 3.0.7 on 2020-07-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteBricks', '0005_auto_20200719_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='property',
            new_name='owner',
        ),
    ]
