# Generated by Django 3.0.7 on 2020-07-20 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WhiteBricks', '0006_auto_20200720_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='person',
        ),
        migrations.AddField(
            model_name='notifications',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WhiteBricks.Property'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
