# Generated by Django 3.0.7 on 2020-08-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteBricks', '0010_auto_20200803_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='occupation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=100, null=True),
        ),
    ]
