# Generated by Django 3.0.7 on 2020-08-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteBricks', '0012_auto_20200804_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='profile_pic'),
        ),
    ]
