# Generated by Django 3.0.7 on 2020-08-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteBricks', '0013_auto_20200805_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verify_otp',
            field=models.IntegerField(null=True),
        ),
    ]
