# Generated by Django 3.0.7 on 2020-08-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteBricks', '0015_auto_20200817_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='type',
            new_name='types',
        ),
    ]
