# Generated by Django 3.0.7 on 2020-08-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteBricks', '0016_auto_20200817_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='types',
            field=models.CharField(choices=[('family', 'family'), ('boys', 'boys'), ('girls', 'girls'), ('any', 'any')], default='Any', max_length=100),
        ),
    ]
