# Generated by Django 3.0.7 on 2020-08-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteBricks', '0018_auto_20200819_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deposite',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
