# Generated by Django 3.0.7 on 2020-08-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteBricks', '0023_auto_20200830_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image1',
            field=models.FileField(default='s.png', null=True, upload_to='media/uploads'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image2',
            field=models.FileField(default='service.png', null=True, upload_to='media/uploads'),
        ),
    ]
