# Generated by Django 3.0.7 on 2021-01-12 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WhiteBricks', '0029_payingguestcheckout'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_location', models.CharField(max_length=255)),
                ('property_rent', models.FloatField()),
                ('property_address', models.CharField(max_length=200)),
                ('checkout_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WhiteBricks.PayingGuestCheckout')),
                ('paying_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
