# Generated by Django 3.0.7 on 2021-01-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteBricks', '0030_bookedproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.FileField(upload_to='media/uploads')),
                ('image2', models.FileField(null=True, upload_to='media/uploads')),
                ('image3', models.FileField(null=True, upload_to='media/uploads')),
            ],
        ),
    ]
