# Generated by Django 3.0.7 on 2021-01-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteBricks', '0032_auto_20210115_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='deposite',
            new_name='deposit',
        ),
    ]
