# Generated by Django 3.0.7 on 2021-01-16 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteBricks', '0033_auto_20210115_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propertyimg', to='WhiteBricks.Property'),
        ),
    ]
