# Generated by Django 3.0.7 on 2021-01-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteBricks', '0034_auto_20210116_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimages',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='propertyimages',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='propertyimages',
            name='image3',
        ),
    ]
