# Generated by Django 3.0.7 on 2021-01-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhiteBricks', '0035_auto_20210118_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingDetails',
        ),
    ]
